### ISSUE TITLE
Rendering issues (unexpected word wrapping, overlapping text)

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1424] opened 2019-05-20 08:41 UTC
Today I noticed that we have a lot of rendering issues on the WebDriver spec. Especially discoverable when scrolling through [Element Send Keys](https://w3c.github.io/webdriver/#element-send-keys):

<img width="903" alt="Screenshot 2019-05-20 at 10 38 56" src="https://user-images.githubusercontent.com/129603/58007882-7e841780-7aeb-11e9-85c7-d3bfe5e1c74d.png">

@AutomatedTester, @shs96c, or @andreastt do you have any idea where this could come from? At least for the unexpectedly wrapped `element` it seems to be a negative margin of 1px.

**Comment by AutomatedTester** [comment] 2019-05-20 20:36
@marcoscaceres I am guessing this is an issue with respec
If I change the following rule to be
```css
dl.switch > dt {
	 text-indent: 1.5em;
	 margin-top: 1em;
	}
``` 

it fixes it

**Comment by andreastt** [comment] 2019-05-20 21:57
I don’t think this is an issue with ReSpec, but rather it is caused by a recent change to the W3C specification styling template https://www.w3.org/StyleSheets/TR/2016/base.css.

Does anyone know what source repository that files lives in? @fantasai?

**Comment by marcoscaceres** [comment] 2019-05-20 23:29
It appears to be a fun mix of things, including updates to Chrome and Firefox's rendering engines, and potentially something silly I did in ReSpec to overcome it: https://github.com/w3c/tr-design/pull/176 

I'll make sure ReSpec is not doing anything here and then hopefully then it can be addressed by https://github.com/w3c/tr-design/pull/176 .

**Comment by marcoscaceres** [comment] 2019-05-21 01:13
Sent a fix on the ReSpec side to fix the incorrectly rendered `var`s.

**Comment by whimboo** [comment] 2019-05-21 08:32
> It appears to be a fun mix of things, including updates to Chrome and Firefox's rendering engines

I don't believe so, at least not for Firefox. I tested with ESR60 yesterday, which also showed this problem, and did get updates on rendering for a year.

But thanks for submitting this PR!

**Comment by marcoscaceres** [comment] 2019-05-21 11:59
Fixing this broke another thing (as always:)) ... need a little bit more time to fix.

**Comment by marcoscaceres** [comment] 2019-05-27 09:25
Ok, fixed in ReSpec 24.21.8... which was just released. A good refresh should do it :) 

![Screenshot 2019-05-27 19 24 35](https://user-images.githubusercontent.com/870154/58410239-1a49f080-80b5-11e9-800f-9af76cb44086.png)

**Comment by andreastt** [comment] 2019-05-27 10:06
Confirmed! Thanks @marcoscaceres.

**Closed by andreastt** 2019-05-27 10:06 UTC

**Comment by whimboo** [comment] 2019-05-27 14:25
@marcoscaceres which change in the Respec fixed that exactly? Just curious. Thanks!

**Comment by marcoscaceres** [comment] 2019-05-27 18:27
https://github.com/w3c/respec/pull/2354
