### ISSUE TITLE
Navigating away from a page with an unload user prompt

### ISSUE THREAD

**Issue by elliterate** [w3c/webdriver#1227] opened 2018-02-14 01:09 UTC
If user prompts spawned in `beforeunload` event handlers are [always dismissed][1] and dismissal means [preferring the "Cancel" action][2], doesn't that mean one would be unable to leave such a page?

[1]: https://github.com/w3c/webdriver/blob/64753c358c5ead682cbe442776ade964767a13ab/webdriver-spec.html#L8871-L8875
[2]: https://github.com/w3c/webdriver/blob/64753c358c5ead682cbe442776ade964767a13ab/webdriver-spec.html#L8925-L8928

**Comment by whimboo** [comment] 2023-04-03 19:37
Duplicate of #1294.

**Closed by whimboo** 2023-04-03 19:37 UTC

**Comment by elliterate** [comment] 2023-04-06 12:54
> Duplicate of #1294.

@whimboo I’m not sure if it’s quite the same. #1294 seems to want a way to allow the handler to block (that is, to be fully exercised) whereas I would argue for there to be a way to (optionally?) force its dismissal (e.g., in tests, where it could prevent test cleanup). Those seem like they might be related but independent concerns.

**Comment by whimboo** [comment] 2023-04-06 19:53
Our handling of `beforeunload` prompts is currently not great and we need to improve. As such please add a comment to the other issue and I'm happy to adjust the summary to match all aspects. We will discuss this topic soon in a WG meeting.
