### ISSUE TITLE
Missing authenticateUsing or some way to interact with authenticationdialogs

### ISSUE THREAD

**Issue by morkeleb** [w3c/webdriver#815] opened 2017-02-25 17:09 UTC
I'm writing [a small tool that stresses webpages with random input](https://github.com/morkeleb/clickmonkey).

It occasionally runs into authentication dialogs opening. I'd like to interact with these dialogs either just close them (as they lock the browser for other input) or to be able to enter text and submit input in them.

There seems to be missing a way to interact with the dialogs in the JSONWire protocol.

**Comment by AutomatedTester** [comment] 2017-02-27 08:39
duplicate of #385

**Closed by AutomatedTester** 2017-02-27 08:39 UTC
