### ISSUE TITLE
Capabilites result's data should be just "capabilities"

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#831] opened 2017-03-02 14:50 UTC
In chapter [8. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-new-session):
> If capabilities result's data is null, return error with error code session not created.

**Comment by AutomatedTester** [comment] 2017-03-07 10:29
duplicate of #830

**Closed by AutomatedTester** 2017-03-07 10:29 UTC
