### ISSUE TITLE
This should also just be /capabilities/

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver#833] opened 2017-03-02 14:57 UTC
In chapter [8. Sessions](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-sessions), section [8.1 New Session](https://w3c.github.io/webdriver/webdriver-spec.html#new-session#h-new-session):
> Let body be a JSON Object initialised with:
> 
> sessionId
>     session id 
> capabilities
>     capabilities result

Sorry for the spam

**Comment by AutomatedTester** [comment] 2017-03-07 11:31
duplicate of #830

**Closed by AutomatedTester** 2017-03-07 11:31 UTC
