### ISSUE TITLE
Missing GetLog command implementation in W3CWireProtocolCommandInfoRepository

### ISSUE THREAD

**Issue by Bazeloth** [w3c/webdriver#1428] opened 2019-06-13 11:24 UTC
The following command seems to be missing:
![image](https://user-images.githubusercontent.com/19928782/59428610-07862a00-8dde-11e9-803d-28c9db938391.png)
_(screenshot is taken from the source of `WebDriverWireProtocolCommandInfoRepository.cs` version 3.141.0.0)_

In the `W3CWireProtocolCommandInfoRepository.cs` class the GetLog method is not implemented. 

Does anyone know whether this got scrapped from the new spec at https://w3c.github.io/webdriver/ ? I cant seem to find it in the Table Of Contents.

We'd like to replace `WebDriverWireProtocolCommandInfoRepository` with `W3CWireProtocolCommandInfoRepository` since its the future spec, but the GetLog command is missing.

**Comment by whimboo** [comment] 2019-06-13 11:29
Dupe of issue #406?

**Comment by Bazeloth** [comment] 2019-06-13 11:45
Thanks for the quick reply @whimboo . Appearently it's not documented in the w3c spec and therefor it hasnt been implemented.

Is there a way to tell them to write the spec for it? To me it's really a missing feature at the moment. We'd like to check for console errors in some situations.

**Comment by whimboo** [comment] 2019-06-14 08:30
Logging is way more complex and got discussed during last years TPAC. See the [meeting minutes](https://www.w3.org/2018/10/25-webdriver-minutes.html#item06) for details. 

If no-one objects I will mark it as dupe of issue #406.

**Closed by whimboo** 2019-06-14 08:30 UTC
