### ISSUE TITLE
Vague behaviour with execute async script and navigations

### ISSUE THREAD

**Issue by gsnedders** [w3c/webdriver#1856] opened 2024-11-05 08:05 UTC
Partly motivated by https://github.com/web-platform-tests/wpt/issues/48825:

What should be the behaviour of:

```
def test_window_navigates(session):
    session.url = "about:blank"
    response = execute_async_script(session, """
        let resolve = arguments[0];
        setTimeout(() => resolve(), 10000);
        location = "about:blank?new_url";
        """)
    assert_error(response, "script timeout")
```

Currently:

 * Firefox gives "javascript error"
 * Chrome gives "script timeout"
 * Safari gives "no such frame"

As far as I can tell, we should fall into:

> If promise is still pending and timer's [timeout fired flag](https://w3c.github.io/webdriver/#dfn-timeout-fired-flag) is set, return [error](https://w3c.github.io/webdriver/#dfn-error) with [error code](https://w3c.github.io/webdriver/#dfn-error-code) [script timeout](https://w3c.github.io/webdriver/#dfn-script-timeout-error).

…because the `setTimeout` call never calls its argument.

And thus the command should always take the current script timeout to complete. (It doesn't in any browser.)

This seems wrong, and we should move towards interop here.

**Comment by whimboo** [comment] 2024-11-05 13:22
This is a dupe of #1708, right?

**Comment by whimboo** [comment] 2024-12-12 10:10
Due to no other objections I'm duping to #1708.

**Closed by whimboo** 2024-12-12 10:10 UTC
Labels: bug, Execute Async Script

**Comment by gsnedders** [comment] 2024-12-12 19:48
Ah, yes. I missed the notification amongst so many others.
