### ISSUE TITLE
some methods about mouse moving cannot work correctly

### ISSUE THREAD

**Issue by Vchenhailong** [w3c/webdriver#1656] opened 2022-05-17 10:06 UTC
https://github.com/SeleniumHQ/selenium/issues/10617

**Comment by whimboo** [comment] 2022-05-17 15:01
The referenced issue has been marked as duplicate of https://github.com/SeleniumHQ/selenium/issues/10601 which itself is closed. By that it's not clear what the problem here actually is. Closing the issue because it's not actionable.

**Closed by whimboo** 2022-05-17 15:01 UTC
