### ISSUE TITLE
Drag N Drop with React is not working

### ISSUE THREAD

**Issue by mkumail22** [w3c/webdriver#1715] opened 2023-01-19 21:07 UTC
When we drag the image file it moves from it source but then unable to reach the destination (drop it )..

Example: Move it from one folder to another folder by DnD.

Browser: Chrome - Version 108.0.5359.125 (Official Build) (32-bit)
Selenium.WebDriver.ChromeDriver" Version="108.0.5359.7100"
Selenium.WebDriver" Version="4.4.0

Here is the example of our code that we are trying ..

![image](https://user-images.githubusercontent.com/123119669/213558333-73da49b7-e803-4dc5-a1de-7f47a7e3376b.png)

This is UI where we are performing drag n drop in media library

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/123119669/213559030-6bd7f0b4-2a61-46f7-9824-19a21d03080f.png)

Please let me know if this issue can be resolved or if there is any workaround for this.. Need your help :-)

**Comment by whimboo** [comment] 2023-01-20 10:31
This sounds like a dupe of #1488.

**Closed by whimboo** 2023-01-20 10:31 UTC
