### ISSUE TITLE
Wrong mathematics at element center calculations

### ISSUE THREAD

**Issue by andreastt** [w3c/webdriver#401] opened 2016-10-04 13:03 UTC
https://www.w3.org/Bugs/Public/show_bug.cgi?id=29776

Aleksey:

> https://www.w3.org/TR/webdriver/#element-click:
> 
> "Let visible width be rect’s bounding rectangle’s (max(x coordinate, x coordinate + width dimension)).
> 
> Let visible height be element’s bounding rectangle’s (max(y coordinate, y coordinate + height dimension)).
> 
> Let vertical centre offset be (visible width / 2.0).
> 
> Let horizontal centre offset be (visible height / 2.0).
> 
> Let centre point be a pair of rect’s (rectangle x coordinate + horizontal centre offset) and (rectangle y coordinate + vertical centre offset)"
> 
> (Let's omit the typo with visible height instead of visible width for horizontal center offset).
> 
> I don't understand such a math:
> 
> Say, x = 100, width = 5.
> 
> x center will be 100 + (100 + 5) / 2 = 152.5.
> And it is out of the right rectancle boundary.
> 
> I think the x center should be calculated as:
> 
> 0.5 \* (max(0, min(x, x + width)) + min(innerWidth, max(x, x + width)))

**Comment by AutomatedTester** [comment] 2016-11-03 22:20
duplicate of #425

**Closed by AutomatedTester** 2016-11-03 22:20 UTC
