### ISSUE TITLE
Enable "preset" of cookies

### ISSUE THREAD

**Issue by tteguayco** [w3c/webdriver#1579] opened 2021-03-16 14:48 UTC
I would like to being able to add a cookie for a certain domain without the need of performing a prior navigation to some URL of that domain for which the cookie is to be added.

Currently we forcedly need to navigate a URL before being able to set a cookie for a domain, when an automation tool such Selenium (using WebDriver behind the scenes to automate the browser). See: https://www.selenium.dev/documentation/en/support_packages/working_with_cookies/

For some scenarios, the information displayed by a web site could depend on cookie configuration. If so, we need to first navigate a given URL, set the cookies and then refresh the page (second navigation) to display the information that wouldn't be displayed without the cookie. Having some sort of way of "presetting" the cookies would save us this second navigation.

**Comment by whimboo** [comment] 2021-03-16 16:45
This is a dupe of #1238.

**Closed by whimboo** 2021-03-16 16:45 UTC
