### ISSUE TITLE
Clarify if timeouts object can be empty

### ISSUE THREAD

**Issue by carlosgcampos** [w3c/webdriver#1136] opened 2017-10-26 14:28 UTC
In WPT there's a test case to check that passing an empty object to timeouts as part of capabilities produces an InvalidArgument error. However, according to the spec, that shouldn't be an error. If this is the intended behavior, then we can simply remove that test case from WPT.

**Comment by andreastt** [comment] 2017-10-31 16:53
Duplicate of https://github.com/w3c/webdriver/issues/1137.

**Closed by andreastt** 2017-10-31 16:53 UTC
