### ISSUE TITLE
User should be able to access JavaScript errors raised by the browser during tests execution

### ISSUE THREAD

**Issue by Flaburgan** [w3c/webdriver#1296] opened 2018-08-31 14:10 UTC
As a developer writing tests,
I want my tests to fail if there are any JavaScript errors thrown during my tests execution.

I don't know if what we want here is to be able to access all the output of the browser console or to give a way for the browser to warn that some errors were encountered. In any case, the developer has to have a way to know errors happened.

**Comment by Flaburgan** [comment] 2018-08-31 14:11
Probably linked to https://github.com/w3c/webdriver/issues/406

**Comment by andreastt** [comment] 2018-08-31 14:52
It is my understanding that WebDriver immediately returns with a `javascript error` when an injected script throws an error. For other errors that happen at runtime, these do not affect the user’s ability to use the browser, which is what WebDriver tries to emulate.

I would probably say that this is a duplicate of https://github.com/w3c/webdriver/issues/406.

**Closed by andreastt** 2018-08-31 14:52 UTC
