### ISSUE TITLE
WebDriver spec should export definitions that are needed to define extension commands

### ISSUE THREAD

**Issue by cbiesinger** [w3c/webdriver#1736] opened 2023-05-08 18:17 UTC
I am writing a spec that wants to define webdriver extension commands, and as such it needs to link to some definitions from the webdriver spec. It would be great if they were marked for export. Specifically I need:

- Error codes <dfn>no such alert</dfn> (https://github.com/w3c/webdriver/blob/master/index.html#L1196)
- "getting a property" (https://github.com/w3c/webdriver/blob/master/index.html#L366)
- <dfn>error code</dfn> (https://github.com/w3c/webdriver/blob/master/index.html#L1096)

**Comment by whimboo** [comment] 2023-05-09 13:25
Dupe of #1598? @cbiesinger would you mind adding your requirements to the other issue so that we only have track a single one? Thanks.

**Closed** 2023-05-09 15:19 UTC
